"""
AgenticOS Multi-Agent and IDE Integration Engine.

Generates thin, standardized configuration adapters for AI coding assistants:
- Google Antigravity (AGY) [Native / Zero-config with optional rule adapter]
- Cursor IDE [.cursorrules]
- VS Code + GitHub Copilot [.github/copilot-instructions.md]
- Claude Code CLI / Anthropic Claude [CLAUDE.md]

ASCII-safe across all Windows, macOS, and Linux terminal encodings.
Zero runtime dependencies (Python standard library only).
"""

from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ANSI color codes
COLOR_RED = "\033[91m"
COLOR_GREEN = "\033[92m"
COLOR_YELLOW = "\033[93m"
COLOR_CYAN = "\033[96m"
COLOR_GRAY = "\033[90m"
COLOR_BOLD = "\033[1m"
COLOR_RESET = "\033[0m"

AGENTICOS_MARKER = "<!-- Generated by AgenticOS (agentic-os ide configure) -->"

IDE_TARGETS: Dict[str, Dict[str, str]] = {
    "antigravity": {
        "name": "Google Antigravity (AGY)",
        "mode": "Native / Zero-config",
        "primary_file": ".agents/rules/agentic-os.md",
        "description": "Natively discovers AGENTS.md and .agents/skills/. Configures optional rule adapter.",
    },
    "cursor": {
        "name": "Cursor IDE",
        "mode": "Convention-based",
        "primary_file": ".cursorrules",
        "description": "Instructs Cursor agent to enforce AGENTS.md invariants and consult .agents/skills/.",
    },
    "copilot": {
        "name": "VS Code + GitHub Copilot",
        "mode": "Convention-based",
        "primary_file": ".github/copilot-instructions.md",
        "description": "Injects AGENTS.md rules and skill catalog triggers into GitHub Copilot instructions.",
    },
    "claude": {
        "name": "Claude Code CLI / Anthropic",
        "mode": "Convention-based",
        "primary_file": "CLAUDE.md",
        "description": "Establishes CLAUDE.md referencing AGENTS.md, uv environment isolation, and skills.",
    },
}


def _colorize(text: str, color: str) -> str:
    if sys.stdout.isatty() or os.getenv("TERM") or os.getenv("COLORTERM"):
        return f"{color}{text}{COLOR_RESET}"
    return text


def list_targets() -> Dict[str, Dict[str, str]]:
    """Returns metadata for all supported IDE integration targets."""
    return IDE_TARGETS.copy()


def print_target_list() -> None:
    """Prints the available IDE integration targets in a clean ASCII table."""
    print(_colorize("\n=======================================================", COLOR_CYAN))
    print(_colorize("         AgenticOS Multi-Agent & IDE Targets           ", COLOR_BOLD + COLOR_CYAN))
    print(_colorize("=======================================================\n", COLOR_CYAN))
    for key, info in IDE_TARGETS.items():
        print(f"  * {_colorize(key, COLOR_BOLD + COLOR_GREEN):<16} {info['name']:<28} [{info['mode']}]")
        print(f"    File: {info['primary_file']}")
        print(f"    Desc: {_colorize(info['description'], COLOR_GRAY)}\n")
    print(_colorize("To configure an IDE target, run:", COLOR_GRAY))
    print(_colorize("  agentic-os ide configure --target <target>\n", COLOR_CYAN))


def build_cursor_rules_content() -> str:
    return f"""{AGENTICOS_MARKER}
# Cursor AI Rules — Powered by AgenticOS

You are working in a repository governed by **AgenticOS**.

## Universal Invariants (Strict Enforcement)
1. **Never install packages globally**. All development must occur inside isolated project virtual environments (`.venv/` or local `node_modules`). Always use `uv run <cmd>` or project tools.
2. **Inspect before modifying**: Read existing files, type contracts, and configuration before applying edits.
3. **Minimal, surgical diffs**: Make the smallest correct change preserving backward compatibility.
4. **Verification before completion**: Execute tests (`uv run pytest`) and linters before reporting complete.
5. **Zero secret leakage**: Never write secrets, keys, or credentials to code or version control.

## Engineering Workflow & Modular Skills
- Consult `AGENTS.md` for the complete non-negotiable invariant rules.
- When performing specialized tasks (API design, ML, database migrations, debugging, docker, etc.), read and follow the corresponding skill instructions located in `.agents/skills/<skill-name>/SKILL.md`.
- Refer to `SKILLS_INDEX.md` for the master trigger matrix.
"""


def build_copilot_instructions_content() -> str:
    return f"""{AGENTICOS_MARKER}
# GitHub Copilot Instructions — Powered by AgenticOS

This workspace follows the **AgenticOS** AI engineering system.

## Core Rules & Invariants
- **Environment Isolation**: Never run bare global package installations. Use project-local environments (`uv run`, `.venv/`).
- **Grounding & Precision**: Always inspect existing implementations and schemas before suggesting edits.
- **Verification**: Ensure all proposed changes are validated with relevant unit and integration tests.
- **Rule Hierarchy**: When resolving conflicts, follow the hierarchy defined in `AGENTS.md`.

## Modular Skill Integration
Specialized workflows are codified in `.agents/skills/`. When performing relevant tasks:
- Python APIs: Refer to `.agents/skills/python-api/SKILL.md`
- Machine Learning: Refer to `.agents/skills/machine-learning/SKILL.md`
- PostgreSQL & Database: Refer to `.agents/skills/database-postgresql/SKILL.md`
- Debugging: Refer to `.agents/skills/debugging/SKILL.md`
- See `SKILLS_INDEX.md` for the full catalog of 30+ engineering skills.
"""


def build_claude_content() -> str:
    return f"""{AGENTICOS_MARKER}
# CLAUDE.md — Powered by AgenticOS

Welcome! This repository uses **AgenticOS** to structure AI-assisted engineering.

## Engineering Invariants
- Always use `uv` for Python project management (`uv venv`, `uv sync`, `uv run pytest`).
- Never pollute the host Python environment.
- Always consult `AGENTS.md` for foundational rules, decision hierarchy, and anti-looping gates.
- When working on complex tasks, activate the relevant modular skill from `.agents/skills/` (see `SKILLS_INDEX.md`).

## Common Commands
```bash
# Run tests
uv run pytest -v

# Run environment health check
agentic-os doctor

# Format and lint
uv run ruff check .
```
"""


def build_antigravity_rule_content() -> str:
    return f"""{AGENTICOS_MARKER}
# Google Antigravity Rule Adapter — Powered by AgenticOS

This workspace is natively configured for **Google Antigravity (AGY)**.

## Native Customizations
- **Universal Invariant Rules**: Discovered directly from `AGENTS.md` in repository root.
- **Modular Skills**: Discovered directly from `.agents/skills/` (30+ domain skills).
- **Deterministic Guard**: Enforced via `hooks/environment_guard.py`.

Antigravity natively loads these assets. Consult `SKILLS_INDEX.md` for skill triggers.
"""


def get_adapter_files(target: str) -> Dict[Path, str]:
    """Returns mapping of relative file paths to their generated adapter content."""
    files: Dict[Path, str] = {}
    if target == "cursor":
        files[Path(".cursorrules")] = build_cursor_rules_content()
    elif target == "copilot":
        files[Path(".github/copilot-instructions.md")] = build_copilot_instructions_content()
    elif target == "claude":
        files[Path("CLAUDE.md")] = build_claude_content()
    elif target == "antigravity":
        files[Path(".agents/rules/agentic-os.md")] = build_antigravity_rule_content()
    elif target == "all":
        files[Path(".cursorrules")] = build_cursor_rules_content()
        files[Path(".github/copilot-instructions.md")] = build_copilot_instructions_content()
        files[Path("CLAUDE.md")] = build_claude_content()
        files[Path(".agents/rules/agentic-os.md")] = build_antigravity_rule_content()
    else:
        raise ValueError(f"Unknown IDE target '{target}'. Valid targets: {list(IDE_TARGETS.keys()) + ['all']}")
    return files


def _files_are_identical(content: str, dst_path: Path) -> bool:
    if not dst_path.exists():
        return False
    try:
        existing = dst_path.read_text(encoding="utf-8")
        return existing.strip() == content.strip()
    except Exception:
        return False


def run_ide_configure(
    target: str,
    project_dir: Path | str = ".",
    force: bool = False,
    dry_run: bool = False,
    quiet: bool = False,
) -> int:
    """
    Configures IDE adapters for target AI assistant with conflict safety.

    Returns:
        0 on success or clean dry-run
        1 on invalid target or unresolved conflicts
    """
    clean_target = (target or "").strip().lower()
    valid_targets = list(IDE_TARGETS.keys()) + ["all"]

    if clean_target not in valid_targets:
        if not quiet:
            print(_colorize(f"\n[FAIL] Unknown IDE target '{target}'.", COLOR_RED))
            print_target_list()
        return 1

    dest_root = Path(os.path.abspath(str(project_dir)))

    try:
        adapters = get_adapter_files(clean_target)
    except ValueError as e:
        if not quiet:
            print(_colorize(f"[FAIL] {e}", COLOR_RED))
        return 1

    if not quiet:
        print(_colorize("\n=======================================================", COLOR_CYAN))
        print(_colorize("        AgenticOS IDE Configuration Generator          ", COLOR_BOLD + COLOR_CYAN))
        print(_colorize("=======================================================\n", COLOR_CYAN))
        print(f"  * Target:          {clean_target} ({'All Supported Assistants' if clean_target == 'all' else IDE_TARGETS[clean_target]['name']})")
        print(f"  * Workspace:       {dest_root}")
        print(f"  * Mode:            {'DRY-RUN (Preview)' if dry_run else 'ACTIVE CONFIGURATION'}")
        print(f"  * Force Overwrite: {'ENABLED' if force else 'DISABLED (Conflict-Safe)'}\n")

    created: List[Path] = []
    skipped: List[Path] = []
    overwritten: List[Path] = []
    conflicted: List[Path] = []

    for rel_path, content in adapters.items():
        dst_file = dest_root / rel_path

        if not dst_file.exists():
            if not dry_run:
                dst_file.parent.mkdir(parents=True, exist_ok=True)
                dst_file.write_text(content, encoding="utf-8")
            created.append(rel_path)
            if not quiet:
                print(f"  {_colorize('[CREATE]', COLOR_GREEN)} {rel_path}")

        elif _files_are_identical(content, dst_file):
            skipped.append(rel_path)
            if not quiet:
                print(f"  {_colorize('[SKIP]', COLOR_GRAY)} {rel_path} (identical)")

        elif force:
            if not dry_run:
                dst_file.parent.mkdir(parents=True, exist_ok=True)
                dst_file.write_text(content, encoding="utf-8")
            overwritten.append(rel_path)
            if not quiet:
                print(f"  {_colorize('[OVERWRITE]', COLOR_YELLOW)} {rel_path} (force)")

        else:
            conflicted.append(rel_path)
            if not quiet:
                print(f"  {_colorize('[CONFLICT]', COLOR_RED)} {rel_path} (already exists with custom content, use --force)")

    if not quiet:
        print(_colorize("\nConfiguration Summary:", COLOR_BOLD))
        print(f"  * Created:     {len(created)}")
        print(f"  * Skipped:     {len(skipped)} (already identical)")
        print(f"  * Overwritten: {len(overwritten)}")
        print(f"  * Conflicts:   {len(conflicted)}")

    if conflicted:
        if not quiet:
            print(_colorize("\n[FAIL] Configuration halted due to existing file conflicts.", COLOR_BOLD + COLOR_RED))
            print("   Pass '--force' to overwrite existing configuration files.\n")
        return 1

    if not quiet:
        if dry_run:
            print(_colorize("\n[PASS] Dry-run complete. No files were written to disk.\n", COLOR_CYAN))
        else:
            print(_colorize(f"\n[PASS] Successfully configured IDE integration for '{clean_target}'!\n", COLOR_BOLD + COLOR_GREEN))

    return 0


def run_ide_doctor(project_dir: Path | str = ".", quiet: bool = False) -> int:
    """
    Inspects and reports active IDE / AI agent adapter configurations.

    Returns:
        0 if at least one adapter is configured or repository is clean
        1 if errors occur
    """
    root = Path(os.path.abspath(str(project_dir)))

    if not quiet:
        print(_colorize("\n=======================================================", COLOR_CYAN))
        print(_colorize("           AgenticOS IDE Integration Doctor           ", COLOR_BOLD + COLOR_CYAN))
        print(_colorize("=======================================================\n", COLOR_CYAN))
        print(f"  * Workspace Path: {root}\n")

    configured_count = 0
    total_count = len(IDE_TARGETS)

    # 1. Antigravity Check (Native Discovery)
    has_agents_md = (root / "AGENTS.md").is_file()
    has_skills = (root / ".agents" / "skills").is_dir()
    has_rule_adapter = (root / ".agents" / "rules" / "agentic-os.md").is_file()

    if has_agents_md and has_skills:
        configured_count += 1
        status = _colorize("[NATIVE PASS]", COLOR_GREEN)
        note = "Native discovery active (AGENTS.md + .agents/skills/)"
        if has_rule_adapter:
            note += " [.agents/rules/agentic-os.md present]"
    elif has_agents_md or has_skills or has_rule_adapter:
        configured_count += 1
        status = _colorize("[PARTIAL]    ", COLOR_YELLOW)
        note = "Partial native assets found (run 'agentic-os init')"
    else:
        status = _colorize("[MISSING]    ", COLOR_YELLOW)
        note = "Native assets not found (run 'agentic-os init')"

    if not quiet:
        print(f"  * {IDE_TARGETS['antigravity']['name']:<28} {status} {note}")

    # 2. Convention-based IDE Checks (Cursor, Copilot, Claude)
    for target_key in ["cursor", "copilot", "claude"]:
        info = IDE_TARGETS[target_key]
        file_path = root / info["primary_file"]
        if file_path.exists():
            configured_count += 1
            status = _colorize("[CONFIGURED] ", COLOR_GREEN)
            note = f"Found {info['primary_file']}"
        else:
            status = _colorize("[MISSING]    ", COLOR_YELLOW)
            note = f"Not configured (run 'agentic-os ide configure --target {target_key}')"

        if not quiet:
            print(f"  * {info['name']:<28} {status} {note}")

    if not quiet:
        print(_colorize(f"\nSummary: {configured_count}/{total_count} IDE integrations active.\n", COLOR_BOLD))
        if configured_count < total_count:
            print(_colorize("Tip: Run 'agentic-os ide configure --target all' to enable all integrations.\n", COLOR_GRAY))

    return 0
